---
name: arm64

on:
  push:

jobs:
  syslog-ng:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up toolchain
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make curl tar
      - name: Fetch syslog-ng
        run: 
          curl -LO https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-4.5.0/syslog-ng-4.5.0.tar.gz
      - name: Untar syslog-ng
        run: |
          tar xzf syslog-ng-4.5.0.tar.gz
      - name: Build dbld image
        env:
          DOCKER_DEFAULT_PLATFORM: linux/arm64
        working-directory: syslog-ng-4.5.0
        run: dbld/rules image-ubuntu-jammy
      - name: Build dbld packages
        env:
          DOCKER_DEFAULT_PLATFORM: linux/arm64
        working-directory: syslog-ng-4.5.0
        run: /dbld/deb
