---
name: arm64

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test QEMU linux/arm64
        env:
          DOCKER_DEFAULT_PLATFORM: linux/arm64
        run: |
          docker run --rm -i alpine:latest sh -c "uname -a"
