---
# yamllint disable rule:line-length
name: repo

# yamllint disable rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REPO_NAME: caddy
  CODENAME: jammy
  COMPONENTS: main
  ARCHITECTURES: amd64 arm64

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
      keyring: ${{ steps.create-apt-repo.outputs.keyring }}
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4
      - name: Install toolchain
        id: install-toolchain
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl
      - name: Fetch packages
        id: fetch-packages
        run: |
          export version=${GITHUB_REF_NAME%%+*}
          export patchlevel=${GITHUB_REF_NAME##*+}
          curl -sfLO https://github.com/caddyserver/caddy/releases/download/${version}/caddy_${version//v/}_linux_arm64.deb
          curl -sfLO https://github.com/caddyserver/caddy/releases/download/${version}/caddy_${version//v/}_linux_amd64.deb
      - uses: morph027/apt-repo-action@main
        id: create-apt-repo
        with:
          repo-name: ${{ env.REPO_NAME }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          codename: ${{ env.CODENAME }}
          components: ${{ env.COMPONENTS }}
          architectures: ${{ env.ARCHITECTURES }}
          import-from-repo-url: |
            deb-amd64 https://skaylink-stefan-heitmueller.github.io/test/ jammy main
            deb-arm64 https://skaylink-stefan-heitmueller.github.io/test/ jammy main
      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ steps.create-apt-repo.outputs.dir }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
      - name: Adding summary
        run: |
          (
              echo "```bash"
              echo "curl -sfLo /etc/apt.trusted.gpg.d/${{ needs.build.outputs.keyring }}.asc ${{ steps.deploy-pages.outputs.page_url }}gpg.key"
              echo "echo \"deb ${{ steps.deploy-pages.outputs.page_url }}/ ${{ env.CODENAME }} ${{ env.COMPONENTS }}\" >/etc/apt/sources.list.d/${{ env.REPO_NAME }}.list"
              echo '```'
          )> ${GITHUB_STEP_SUMMARY}
