---
# yamllint disable rule:line-length
name: repo

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4
      - name: Install toolchain
        id: install-toolchain
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl
      - name: Fetch packages
        id: fetch-packages
        run: |
          curl -sfLO https://github.com/caddyserver/caddy/releases/download/v2.7.5/caddy_2.7.5_linux_arm64.deb
          curl -sfLO https://github.com/caddyserver/caddy/releases/download/v2.7.5/caddy_2.7.5_linux_amd64.deb
      - uses: skaylink-stefan-heitmueller/create-apt-repo@latest
        id: create-apt-repo
        with:
          repo-name: caddy
          signing-key: ${{ secrets.SIGNING_KEY }}
          codename: jammy
          architectures: amd64 arm64
          import-from-repo-url: |
            deb-amd64 https://skaylink-stefan-heitmueller.github.io/test/ jammy main
            deb-arm64 https://skaylink-stefan-heitmueller.github.io/test/ jammy main
      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ steps.create-apt-repo.outputs.repodir }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
