---
# yamllint disable rule:line-length
name: webhook
run-name: webhook-${{ github.event.inputs.uuid }}

# yamllint disable rule:truthy
on:
  workflow_dispatch:
    inputs:
      uuid:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        run: |
          echo Test
