---
# yamllint disable rule:line-length
name: webhook

# yamllint disable rule:truthy
on:
  workflow_dispatch:
    inputs:
      uuid:
        type: string
        required: true
  repository_dispatch:
    types:
      - webhook

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook [${{ github.event.inputs.uuid }}]
        run: |
          echo Test
